<?php

/**
 * PluginsfOpenAuthUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfOpenAuthUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfOpenAuthUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfOpenAuthUser');
    }
}